const SUPABASE_URL=process.env.SUPABASE_URL||'https://dddthwakdrxxmjbfowpl.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_f3QAMeX2YKuyeOI3WMkhng_9LdWdL7O';
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
async function verifyFieldOpsKey(key){if(!key)return false;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/fieldops_key_status`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json','x-fieldops-key':key},body:'{}'});return r.ok&&(await r.json().catch(()=>false))===true;}
async function rest(path,{method='GET',body,prefer='return=representation'}={}){if(!SERVICE_KEY)throw new Error('Server database access is not configured');const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();const j=t?JSON.parse(t):null;if(!r.ok)throw new Error(j?.message||j?.hint||`Database request failed (${r.status})`);return j;}
const uuid=v=>/^[0-9a-f-]{36}$/i.test(String(v||''));
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{if(!(await verifyFieldOpsKey(String(req.headers['x-fieldops-key']||''))))return res.status(401).json({error:'Authentication required'});const id=String(req.body?.job_id||'');if(!uuid(id))return res.status(400).json({error:'Invalid job'});const jobs=await rest(`jobs?id=eq.${encodeURIComponent(id)}&select=*`);const job=jobs?.[0];if(!job)return res.status(404).json({error:'Job not found'});const now=new Date().toISOString();await rest(`jobs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{status:'completed',updated_at:now},prefer:'return=minimal'});
const existing=await rest(`invoices?job_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=1`);if(existing?.length)return res.status(200).json({completed:true,existing:true,invoice_id:existing[0].id});
let estimate=null,items=[];const estimates=await rest(`estimates?job_id=eq.${encodeURIComponent(id)}&status=eq.approved&select=*&order=approved_at.desc.nullslast,created_at.desc&limit=1`);if(estimates?.length){estimate=estimates[0];items=await rest(`estimate_items?estimate_id=eq.${encodeURIComponent(estimate.id)}&select=*&order=sort_order.asc,created_at.asc`);}else{const mats=await rest(`job_materials?job_id=eq.${encodeURIComponent(id)}&billable=eq.true&select=*&order=created_at.asc`);items=(mats||[]).map((m,i)=>({description:m.description||'Material',quantity:Number(m.quantity||1),unit_price:Number(m.unit_price||0),line_total:Number(m.quantity||1)*Number(m.unit_price||0),sort_order:i}));}
if(!items.length){const fallbackTotal=Number(job.total||job.price||job.amount||job.quoted_total||0);items=[{description:job.title||job.service_type||job.job_type||'Completed plumbing service',quantity:1,unit_price:fallbackTotal,line_total:fallbackTotal,sort_order:0}];}
const subtotal=items.reduce((a,x)=>a+Number(x.line_total??Number(x.quantity||1)*Number(x.unit_price||0)),0);const payload={customer_id:estimate?.customer_id||job.customer_id,status:'draft',subtotal:estimate?Number(estimate.subtotal??subtotal):subtotal,tax:estimate?Number(estimate.tax||0):0,total:estimate?Number(estimate.total??subtotal):subtotal,description:estimate?.description||job.notes||job.description||null,title:estimate?.title||job.title||job.service_type||job.job_type||'Completed service',job_id:id};if(estimate)payload.estimate_id=estimate.id;if(!payload.customer_id)throw new Error('This job is missing a customer. Add the customer before completing it.');const inserted=await rest('invoices',{method:'POST',body:payload});const invoice=inserted?.[0];if(!invoice)throw new Error('Invoice was not created');const invoiceItems=items.map((x,i)=>({invoice_id:invoice.id,description:x.description||'Line item',quantity:Number(x.quantity||1),unit_price:Number(x.unit_price||0),line_total:Number(x.line_total??Number(x.quantity||1)*Number(x.unit_price||0)),sort_order:x.sort_order??i}));await rest('invoice_items',{method:'POST',body:invoiceItems});return res.status(200).json({completed:true,existing:false,invoice_id:invoice.id});}catch(e){return res.status(500).json({error:e?.message||'Could not complete job'});}}
