const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const monthOf=date=>Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'numeric'}).format(new Date(date)))-1;
export function monthlyFinance(entries,payments){
 const months=Array.from({length:12},(_,m)=>({label:new Date(2026,m,1).toLocaleString('en-US',{month:'short'}),income:0,spending:0,movement:0}));
 for(const p of payments){if(!['paid','succeeded','completed'].includes(p.status))continue;const m=monthOf(p.paid_at);if(!months[m])continue;months[m].income+=Math.round(Number(p.amount)*100);months[m].movement+=Math.round(Number(p.amount)*100);}
 for(const e of entries){if(e.status!=='paid'||e.voided_at)continue;const m=Number(String(e.entry_date).slice(5,7))-1;if(!months[m])continue;const cents=Math.round(Number(e.amount)*100);if(e.kind==='expense')months[m].spending+=cents;months[m].movement+=['loan_received','owner_contribution'].includes(e.kind)?cents:-cents;}
 let cumulative=0;return months.map(m=>{cumulative+=m.movement;return {...m,income:m.income/100,spending:m.spending/100,movement:m.movement/100,cumulative:cumulative/100};});
}
export function lineChart(container,labels,series,title){
 container.replaceChildren();const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 700 255');svg.setAttribute('role','img');svg.setAttribute('aria-label',title);const t=document.createElementNS(ns,'title');t.textContent=title;svg.append(t);const values=series.flatMap(s=>s.values),low=Math.min(0,...values),high=Math.max(1,...values),span=high-low;
 const X=i=>65+i*615/Math.max(1,labels.length-1),Y=v=>205-(v-low)/span*170;
 const el=(tag,attrs,text)=>{const x=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))x.setAttribute(k,String(v));if(text)x.textContent=text;svg.append(x);return x;};
 for(let i=0;i<=4;i++){const v=low+span*i/4;el('line',{x1:65,x2:680,y1:Y(v),y2:Y(v),stroke:'#d8d3ca'});el('text',{x:59,y:Y(v)+4,'text-anchor':'end','font-size':11,fill:'#405666'},money(v));}
 labels.forEach((l,i)=>el('text',{x:X(i),y:227,'text-anchor':'middle','font-size':11,fill:'#405666'},l));
 for(const s of series){el('polyline',{points:s.values.map((v,i)=>`${X(i)},${Y(v)}`).join(' '),fill:'none',stroke:s.color,'stroke-width':3});s.values.forEach((v,i)=>el('circle',{cx:X(i),cy:Y(v),r:3,fill:s.color}));}
 container.append(svg);const legend=document.createElement('p');legend.className='meta';legend.textContent=series.map(s=>s.name).join(' · ');container.append(legend);
 const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='View exact figures';detail.append(summary);const table=document.createElement('table');table.style.width='100%';const head=document.createElement('tr');for(const s of ['Period',...series.map(s=>s.name)]){const th=document.createElement('th');th.textContent=s;head.append(th);}table.append(head);labels.forEach((label,i)=>{const row=document.createElement('tr');for(const v of[label,...series.map(s=>money(s.values[i]))]){const td=document.createElement('td');td.textContent=v;row.append(td);}table.append(row);});detail.append(table);container.append(detail);
}
export function renderTrajectory(host,state,calculation){
 host.replaceChildren();const add=(title,note,labels,series)=>{const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.className='meta';p.textContent=note;const chart=document.createElement('div');chart.className='finance-chart';host.append(h,p,chart);lineChart(chart,labels,series,title);};
 if(state){const all=monthlyFinance(state.entries,state.payments),now=new Date(),count=state.year===now.getFullYear()?now.getMonth()+1:state.year>now.getFullYear()?0:12,months=all.slice(0,count);if(months.length){add('Income & spending','Recorded customer collections include refunds and may include sales tax. Spending shows paid expense entries only. Missing entries make this incomplete; future months are omitted.',months.map(m=>m.label),[{name:'Collections (navy)',color:'#173b53',values:months.map(m=>m.income)},{name:'Expenses (red)',color:'#af263d',values:months.map(m=>m.spending)}]);add('Recorded cash movement','Running total starts at $0 on January 1. Includes loans, owner transfers and principal payments. This is not your bank balance or profit.',months.map(m=>m.label),[{name:'Cumulative recorded movement',color:'#2d7663',values:months.map(m=>m.cumulative)}]);}}
 if(calculation){const c=calculation;add('12-month operating scenario','Illustration only: assumes the same billable capacity and costs every month, all labor sold and collected, and no seasonality. Excludes job materials, sales tax, loan principal and truck-fee income. Negative values mean the modeled hourly rate does not cover the entered operating costs.',Array.from({length:12},(_,i)=>String(i+1)),[{name:'Surplus at current rate (navy)',color:'#173b53',values:Array.from({length:12},(_,i)=>c.annualRateGap*(i+1)/12)},{name:'Surplus at target rate (green)',color:'#2d7663',values:Array.from({length:12},(_,i)=>(c.targetRate*c.annualHours-c.operatingCost)*(i+1)/12)}]);}
 if(!host.children.length)host.textContent='Refresh records or complete the hourly calculator to see the charts.';
}
