import {remodelInput,priceRemodel} from './remodel-pricing.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD'});
const key='a1_remodel_intake_v2';
const box=document.createElement('section');box.id='remodelQuoter';box.hidden=true;box.className='remodel-quoter';
box.innerHTML=`<div class="remodel-heading"><div><p class="eyebrow">PROJECT STUDIO</p><h2>Remodel Estimator</h2><p>Write the scope yourself, identify who supplies each material, and set your own labor rate.</p></div><button type="button" id="closeRemodel">Close</button></div>
<form id="remodelForm">
<fieldset><legend>01 · Scope of work</legend>
<div class="remodel-grid"><label>Project / customer<input name="project" maxlength="240" placeholder="Example: Matt O'Brien — Wakefield House"></label><label>Job location / rooms<input name="location" maxlength="240" placeholder="Address, rooms, or floors"></label></div>
<label>Describe all work<textarea name="scope" required minlength="15" maxlength="8000" placeholder="Type the scope in your own words. You can organize it by room, such as Basement Bathroom, Kitchen, First Floor Bathroom..."></textarea></label>
<div class="remodel-grid"><label>Materials supplied by A-1<textarea name="contractorMaterials" maxlength="4000" placeholder="Pipe, fittings, valves, connectors, consumables, or other items you will buy"></textarea></label><label>Materials supplied by customer<textarea name="customerMaterials" maxlength="4000" placeholder="Fixtures or equipment the homeowner or contractor will provide"></textarea></label></div>
</fieldset>
<fieldset><legend>02 · Price</legend>
<div class="remodel-grid"><label>Labor hours<input name="laborHours" type="number" min="0" max="5000" step="0.25" required value="0"></label><label>Your hourly rate ($)<input name="laborRate" type="number" min="0" max="5000" step="0.01" required value="200"></label><label>Your material purchase cost ($)<input name="materialCost" type="number" min="0" max="1000000" step="0.01" placeholder="Leave blank until priced"></label><label>Material markup (%)<input name="markup" type="number" min="0" max="100" value="25" required></label><label>Permit & outside costs ($)<input name="fees" type="number" min="0" max="100000" step="0.01" placeholder="Leave blank until confirmed"></label></div>
<p class="meta">Customer-supplied materials are listed in the proposal but are never charged. Markup applies only to the materials you buy.</p>
</fieldset>
<fieldset><legend>03 · Responsibilities and notes</legend>
<div class="remodel-grid"><label>Who handles what?<textarea name="responsibilities" maxlength="4000" placeholder="Demolition, framing, electrical, tile, wall repair, cleanup"></textarea></label><label>Permits, timing, and site conditions<textarea name="permits" maxlength="4000" placeholder="Permit responsibility, inspections, access, rough/finish visits"></textarea></label></div>
<label>Explicit exclusions<textarea name="exclusions" maxlength="4000" placeholder="Anything outside this plumbing scope"></textarea></label>
</fieldset>
<div class="remodel-actions"><button class="convert" type="submit">Build proposal</button><button type="button" id="aiRemodel">✦ Optional: polish scope with AI</button><button type="button" id="clearRemodel">Clear intake</button></div>
<p id="remodelStatus" role="status" class="meta"></p></form><div id="remodelResult" aria-live="polite"></div>`;
$('#estimateForm').before(box);
const open=$('#newEstimateBtn');open.textContent='Start Estimate';const type=document.createElement('select');type.id='estimateType';type.setAttribute('aria-label','Estimate type');type.innerHTML='<option value="service">Service / Repair</option><option value="remodel">New Construction / Remodel</option>';open.before(type);
const form=$('#remodelForm');let draft=null,inputSnapshot='';
function inputs(){return Object.fromEntries(new FormData(form));}
function resetResult(){draft=null;$('#remodelResult').innerHTML='';}
function save(){try{localStorage.setItem(key,JSON.stringify(inputs()));$('#remodelStatus').textContent='Intake saved on this device. Nothing has been sent.';}catch{$('#remodelStatus').textContent='Recovery storage is unavailable. Keep this page open.';}}
try{const v=JSON.parse(localStorage.getItem(key)||'null');if(v)for(const el of form.elements)if(el.name&&v[el.name]!==undefined)el.value=v[el.name];}catch{}
open.addEventListener('click',e=>{if(type.value!=='remodel'){box.hidden=true;return;}e.preventDefault();e.stopImmediatePropagation();$('#estimateForm').style.display='none';box.hidden=false;box.scrollIntoView({behavior:'smooth',block:'start'});},true);
type.addEventListener('change',()=>{box.hidden=true;$('#remodelStatus').textContent=type.value==='remodel'?'Click Start Estimate to open the construction/remodel form.':'Click Start Estimate to open the service/repair form.';});
$('#closeRemodel').onclick=()=>{box.hidden=true;open.focus();};
$('#clearRemodel').onclick=()=>{if(!confirm('Clear this remodel intake? Saved quotes stay unchanged.'))return;form.reset();form.laborRate.value='200';form.markup.value='25';resetResult();localStorage.removeItem(key);$('#remodelStatus').textContent='';};
form.addEventListener('input',()=>{draft=null;$('#remodelResult').innerHTML='';save();});
form.onsubmit=e=>{e.preventDefault();try{const x=inputs();remodelInput(x);inputSnapshot=JSON.stringify(x);render(x);$('#remodelStatus').textContent='Proposal ready for your review. Nothing has been saved or sent.';}catch(err){$('#remodelStatus').textContent=err.message;}};
$('#aiRemodel').onclick=async e=>{const btn=e.currentTarget;let x;try{x=inputs();remodelInput(x);}catch(err){$('#remodelStatus').textContent=err.message;return;}btn.disabled=true;$('#remodelStatus').textContent='Polishing your wording…';try{const r=await fetch('/api/documents?feature=remodel-assist',{method:'POST',headers:{'Content-Type':'application/json','x-fieldops-key':window.A1RemodelBridge.key()},body:JSON.stringify(x)}),j=await r.json();if(!r.ok)throw Error(j.error||'AI assistance is unavailable.');draft=j.draft;inputSnapshot=JSON.stringify(x);render(x);$('#remodelStatus').textContent='AI wording added. Review it before using the quote.';}catch(err){$('#remodelStatus').textContent=err.message+' You can still build the proposal manually.';}finally{btn.disabled=false;}};
function render(x){const q=priceRemodel(x,draft);$('#remodelResult').innerHTML=`<div class="remodel-proposal"><p class="eyebrow">${q.isBudget?'BUDGET · REVIEW REQUIRED':'PROPOSED FIXED PRICE · OWNER REVIEW'}</p><div class="remodel-heading"><h3>${esc(x.project||'Remodel')}</h3><strong class="remodel-total">${money(q.total)}</strong></div><p class="meta">${q.laborHours} hours × ${money(q.rate)}/hour = ${money(q.labor)} labor · A-1 materials ${money(q.materials)}</p><div class="remodel-scope-preview">${esc(q.description).replace(/\n/g,'<br>')}</div>${q.checks.length?`<div class="remodel-review"><h3>Confirm before a firm quote</h3><ul>${q.checks.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>`:''}<label class="remodel-approval"><input id="reviewRemodel" type="checkbox"> I reviewed the scope, price, supplied materials, and exclusions.</label><button type="button" id="applyRemodel" class="convert" disabled>Use in draft quote</button><p class="meta">Next, choose the client and job, review the line items, and save. This does not send the quote.</p></div>`;$('#reviewRemodel').onchange=e=>$('#applyRemodel').disabled=!e.target.checked;$('#applyRemodel').onclick=async()=>{if(inputSnapshot!==JSON.stringify(inputs())||!$('#reviewRemodel').checked)return;const btn=$('#applyRemodel');btn.disabled=true;try{const applied=await window.A1RemodelBridge.apply({title:`Remodel — ${x.project||'Project'}`,description:q.description,items:q.items,difficulty:'standard'});if(applied){box.hidden=true;$('#estimateForm').scrollIntoView({behavior:'smooth',block:'start'});}}catch(err){$('#remodelStatus').textContent=err.message;}finally{btn.disabled=false;}};}
