import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import {startServer} from './dev-server.js';
test('desktop and mobile: estimate → signature → change order → completion → payment → receipt',async()=>{
 const app=await startServer(),browser=await chromium.launch({headless:true}),errors=[];
 try{await fs.mkdir('test-results',{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('https://*.supabase.co/**',async route=>{const req=route.request();const response=await fetch(app.origin+'/__rest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:req.url(),options:{method:req.method(),headers:req.headers(),body:req.postData()}})});await route.fulfill({status:response.status(),contentType:'application/json',body:await response.text()});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(app.origin);await page.locator('#accessKey').fill('test-key');await page.getByRole('button',{name:'Unlock FieldOps'}).click();await page.locator('#app').waitFor({state:'visible'});await page.getByRole('button',{name:'Estimates',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#estimates').textContent.includes('Water heater'));await page.evaluate(id=>openEstimate(id),app.estimate);await page.locator('#signatureStatus-'+app.estimate).getByRole('button',{name:'Review / E-Sign'}).waitFor();
 await page.getByRole('button',{name:'View Quote / PDF'}).click();await page.locator('.customer-document').waitFor();await page.screenshot({path:'test-results/desktop-document.png',fullPage:true});assert.equal(await page.locator('.cd-logo').evaluate(e=>e.naturalWidth>0),true);await page.locator('#closeDocumentBtn').click();
 const api=async(path,body)=>{const r=await fetch(app.origin+path,{method:'POST',headers:{'Content-Type':'application/json','x-fieldops-key':'test-key'},body:JSON.stringify(body)});const j=await r.json();assert.equal(r.status,200,JSON.stringify(j));return j;};
 const link=await api('/api/send-document',{kind:'estimate',id:app.estimate,action:'link'});
 const signing=await context.newPage();signing.on('pageerror',e=>errors.push(e.message));await signing.goto(link.signing_url);await signing.locator('#sig').waitFor();await signing.locator('#name').fill('Test Customer');await signing.locator('#sign').click();assert.match(await signing.locator('#msg').textContent(),/draw your signature/);
 async function draw(p){const box=await p.locator('#sig').boundingBox();await p.mouse.move(box.x+30,box.y+45);await p.mouse.down();await p.mouse.move(box.x+120,box.y+70,{steps:12});await p.mouse.move(box.x+200,box.y+25,{steps:12});await p.mouse.up();}
 await draw(signing);await signing.locator('#clear').click();await signing.locator('#sign').click();assert.match(await signing.locator('#msg').textContent(),/draw your signature/);await draw(signing);await signing.locator('#sign').click();await signing.getByRole('link',{name:'Download signed PDF'}).waitFor();assert.equal(app.mails.length,2);const signedBefore=await app.q('select snapshot,signed_pdf_sha256 from fieldops_documents where source_id=$1',[app.estimate]);assert.ok(signedBefore[0].signed_pdf_sha256);
 const co=await api('/api/update-invoice',{kind:'estimate',id:app.estimate,title:'Water heater + expansion tank',description:'Add expansion tank.',items:[{description:'Full revised water heater scope',quantity:1,unit_price:2900}]});assert.equal(co.total,400);
 const coLink=await api('/api/send-document',{kind:'change_order',id:co.change_order_id,action:'link'});await signing.setViewportSize({width:390,height:844});await signing.goto(coLink.signing_url);await signing.locator('#sig').waitFor();assert.match(await signing.locator('.cd-change').textContent(),/\$400.00/);assert.equal(await signing.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await signing.screenshot({path:'test-results/mobile-change-order.png',fullPage:true});await signing.locator('#name').fill('Test Customer');await draw(signing);await signing.locator('#sign').click();await signing.getByRole('link',{name:'Download signed PDF'}).waitFor();
 const completion=await api('/api/complete-job',{job_id:app.job});assert.ok(completion.invoice_id);const completionLink=await api('/api/send-document',{kind:'completion',id:completion.invoice_id,action:'link'});await signing.goto(completionLink.signing_url);await signing.locator('#name').fill('Test Customer');await signing.locator('#exceptions').fill('Touch-up paint remains excluded.');await draw(signing);await signing.locator('#sign').click();await signing.getByRole('link',{name:'Download signed PDF'}).waitFor();
 const paymentRequest={action:'payment',id:completion.invoice_id,amount:1000,method:'check',request_id:crypto.randomUUID()};const payment=await api('/api/documents',paymentRequest);assert.equal(Number(payment.balance),1500);assert.equal((await api('/api/documents',paymentRequest)).already_recorded,true);await api('/api/documents',{...paymentRequest,amount:1500,request_id:crypto.randomUUID()});assert.equal((await app.q('select status from invoices where id=$1',[completion.invoice_id]))[0].status,'paid');
 await page.locator('#closeEstimateModal').click();await page.getByRole('button',{name:'Invoices',exact:true}).click();await page.evaluate(id=>openInvoice(id),completion.invoice_id);await page.getByRole('button',{name:'Receipt / PDF'}).click();await page.locator('.customer-document').waitFor();assert.match(await page.locator('.cd-totals').textContent(),/\$0.00/);await page.screenshot({path:'test-results/desktop-receipt.png',fullPage:true});
 await page.setViewportSize({width:375,height:812});await page.screenshot({path:'test-results/mobile-receipt.png',fullPage:true});assert.equal(await page.locator('.customer-document').evaluate(e=>e.scrollWidth<=e.clientWidth),true);const signedAfter=await app.q('select snapshot,signed_pdf_sha256 from fieldops_documents where source_id=$1',[app.estimate]);assert.deepEqual(signedAfter,signedBefore);assert.deepEqual(errors,[]);
 }finally{await browser.close();await app.close();}
});
