import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
test('signature pad handles touch coordinates, ignores a second finger, clears ink and prevents blank acceptance',async()=>{
 const html=fs.readFileSync(new URL('../customer-sign.html',import.meta.url),'utf8');
 const paths=[],context2d={fillRect(){},beginPath(){},moveTo(...p){paths.push(p)},lineTo(...p){paths.push(p)},stroke(){}};
 const elements={sig:{width:900,height:350,getContext:()=>context2d,getBoundingClientRect:()=>({left:10,top:20,width:360,height:140}),setPointerCapture(){}},clear:{},sign:{},name:{value:'Test Customer'},msg:{}};
 const ctx=vm.createContext({document:{getElementById:id=>elements[id]},canvas:null,ctx:null,drawing:false,hasInk:false,saving:false,activePointer:null});
 const source=html.slice(html.indexOf('function setupCanvas()'),html.indexOf('async function load()'));
 vm.runInContext(source,ctx);vm.runInContext('setupCanvas()',ctx);
 const e=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,preventDefault(){}});
 elements.sig.onpointerdown(e(1,10,20));elements.sig.onpointerdown(e(2,100,100));elements.sig.onpointermove(e(2,150,100));assert.equal(paths.length,1);
 elements.sig.onpointermove(e(1,190,90));assert.deepEqual(paths[1],[450,175]);assert.equal(ctx.hasInk,true);
 elements.sig.onpointercancel(e(1));assert.equal(ctx.drawing,false);
 elements.clear.onclick();assert.equal(ctx.hasInk,false);
 await vm.runInContext('sign()',ctx);assert.match(elements.msg.textContent,/draw your signature/);
});
test('invoice typed signature requires name, fits the canvas and clears stale signature',async()=>{
 const html=fs.readFileSync(new URL('../customer-sign.html',import.meta.url),'utf8');const written=[];
 const context2d={fillRect(){},fillText(...args){written.push(args)},measureText:t=>({width:t.length*15})};
 const elements={sig:{getContext:()=>context2d},name:{value:''},sign:{},msg:{}};
 const ctx=vm.createContext({document:{getElementById:id=>elements[id],fonts:{load:async()=>[],check:()=>true}},canvas:null,ctx:null,hasInk:false,saving:false,sign(){}});
 vm.runInContext(html.slice(html.indexOf('async function setupTypedSignature()'),html.indexOf('function setupCanvas()')),ctx);
 await vm.runInContext('setupTypedSignature()',ctx);assert.equal(ctx.hasInk,false);
 elements.name.value='Sample Customer';await elements.name.oninput();assert.equal(ctx.hasInk,true);assert.equal(written.at(-1)[0],'Sample Customer');assert.equal(written.at(-1)[1],450);
 elements.name.value='';await elements.name.oninput();assert.equal(ctx.hasInk,false);
 assert.match(html,/required minlength="2" maxlength="120"/);
 assert.match(html,/s.kind==='completion'\?'<label for="exceptions">/);
});
