import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {monthlyFinance} from '../finance-charts.js';
import {hourlyCost} from '../hourly-cost.js';
import {financeTotals} from '../lib/finance.js';
import {startServer} from './dev-server.js';
const inputs={technicians:2,wage:30,paidHours:2000,burden:25,billableHours:1000,overhead:4000,ownerPay:1000,debtPrincipal:500,margin:20,currentRate:165};
test('cost model divides by billable capacity and uses margin, not markup',()=>{const c=hourlyCost(inputs);assert.equal(c.annualLabor,150000);assert.equal(c.breakEven,105);assert.equal(c.targetRate,131.25);assert.equal(c.cashCoverageRate,108);assert.equal(c.utilization,50);assert.throws(()=>hourlyCost({...inputs,billableHours:0}));assert.throws(()=>hourlyCost({...inputs,billableHours:2001}));assert.throws(()=>hourlyCost({...inputs,overhead:''}));assert.throws(()=>hourlyCost({...inputs,margin:100}));});
test('cash totals exclude pending transactions and keep funding separate from sales',()=>{const totals=financeTotals([{kind:'expense',amount:30.12,status:'paid'},{kind:'expense',amount:9,status:'paid',voided_at:'today'},{kind:'expense',amount:40,status:'due'},{kind:'loan_received',amount:10000,status:'paid'},{kind:'loan_principal',amount:500,status:'paid'}],[{amount:100,status:'completed'},{amount:-25,status:'completed'},{amount:900,status:'pending'}]);assert.equal(totals.collections,75);assert.equal(totals.expenses,30.12);assert.equal(totals.billsDue,40);assert.equal(totals.loanReceived,10000);assert.equal(totals.loanPrincipal,500);});
test('owner finance API keeps records private, validates and deduplicates saves',async()=>{const app=await startServer();try{const call=async(op,body={},key='test-key')=>{const r=await fetch(app.origin+'/api/documents',{method:'POST',headers:{'content-type':'application/json','x-fieldops-key':key},body:JSON.stringify({action:'tools',op,...body})});const data=await r.json();return {status:r.status,data};};assert.equal((await call('finance-snapshot',{year:2026},'')).status,401);assert.equal((await call('finance-profile',{inputs})).status,200);const entry={id:randomUUID(),entry_date:'2026-09-11',kind:'expense',category:'Fuel',payee:'Fuel station',amount:45.99,status:'paid',notes:'Receipt 123'};assert.equal((await call('finance-entry',entry)).status,200);assert.equal((await call('finance-entry',entry)).status,200);assert.notEqual((await call('finance-entry',{...entry,amount:46})).status,200);assert.notEqual((await call('finance-entry',{...entry,id:randomUUID(),entry_date:'2026-02-30'})).status,200);let snapshot=await call('finance-snapshot',{year:2026});assert.equal(snapshot.status,200,JSON.stringify(snapshot.data));assert.equal(snapshot.data.entries.length,1);assert.equal(snapshot.data.totals.expenses,45.99);assert.equal(snapshot.data.calculation.targetRate,131.25);assert.equal((await call('finance-void',{id:entry.id,reason:'Wrong receipt'})).status,200);assert.equal((await call('finance-snapshot',{year:2026})).data.totals.expenses,0);assert.equal((await app.q('select void_reason from fieldops_finance_entries where id=$1',[entry.id]))[0].void_reason,'Wrong receipt');for(const table of ['fieldops_cost_profile','fieldops_finance_entries'])for(const role of ['anon','authenticated'])assert.equal((await app.q('select has_table_privilege($1,$2,\'SELECT\') as allowed',[role,table]))[0].allowed,false);}finally{await app.close();}});

test('trajectory uses Boston payment dates and excludes unpaid or voided spending',()=>{const m=monthlyFinance([{entry_date:'2026-02-01',kind:'expense',amount:50,status:'paid'},{entry_date:'2026-02-02',kind:'loan_received',amount:1000,status:'paid'},{entry_date:'2026-02-03',kind:'expense',amount:999,status:'due'}],[{paid_at:'2026-02-01T02:00:00Z',amount:100,status:'completed'}]);assert.equal(m[0].income,100);assert.equal(m[1].spending,50);assert.equal(m[1].cumulative,1050);});

test('pagination does not silently omit entries and AI receives aggregates only',async()=>{const app=await startServer();try{await app.q("insert into fieldops_finance_entries(id,entry_date,kind,category,payee,amount,status,notes) select gen_random_uuid(),'2026-09-01','expense','Other','Private payee',1,'paid','Private note' from generate_series(1,501)");const call=async(op)=>{const r=await fetch(app.origin+'/api/documents',{method:'POST',headers:{'content-type':'application/json','x-fieldops-key':'test-key'},body:JSON.stringify({action:'tools',op,year:2026,inputs})});return r.json();};const snap=await call('finance-snapshot');assert.equal(snap.entries.length,501);assert.equal(snap.totals.expenses,501);const previous=global.fetch;let ai;global.fetch=async(url,options)=>{if(String(url)==='https://api.openai.com/v1/responses'){ai=JSON.parse(options.body);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:'Review your receipts and billable hours.'}]}]});}return previous(url,options);};try{assert.match((await call('finance-advice')).advice,/receipts/);assert.equal(ai.store,false);assert.equal(ai.reasoning.effort,'high');assert.ok(!ai.input.includes('Private payee'));assert.ok(!ai.input.includes('Private note'));}finally{global.fetch=previous;}}finally{await app.close();}});
